on: [push, pull_request]

jobs:
  compatibility-check:
    runs-on: ubuntu-latest
    name: Check compatibility with previous levitate versions
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: yarn install
      - name: Build plugin
        run: yarn build
      - name: Compatibility check
        uses: grafana/levitate/actions/is-compatible
        with:
          module: "./src/bin.ts"
          comment-pr: 'yes'
          fail-if-incompatible: 'yes'
          target: '@grafana/levitate@latest'
